# Generated by Django 5.2.1 on 2026-03-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('agreement', 'Agreement'), ('aadhar', 'Aadhar'), ('pan', 'PAN'), ('gst', 'GST'), ('license', 'License'), ('receipt', 'Receipt'), ('invoice', 'Invoice'), ('tax', 'Tax'), ('eb_bill', 'EB Bill'), ('property_tax_receipt', 'Property Tax Receipt'), ('water_tax_receipt', 'Water Tax Receipt'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Deposit'), ('maintenance', 'Maintenance'), ('tax', 'Tax'), ('utility', 'Utility'), ('property_tax', 'Property Tax'), ('water_tax', 'Water Tax'), ('eb_deposit', 'EB Deposit'), ('other', 'Other')], max_length=20),
        ),
    ]
