# Generated by Django 5.2.1 on 2026-03-07 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialTenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('family_size', models.PositiveIntegerField(default=1)),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residential_profile', to='common.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
